title: "Tutor's Pet"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

kramdown:
  toc_levels: [1,2,3,4]

repository: "AY2021S1-CS2103T-T10-4/tp"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
